parameters:
    # Adds a fallback VARNISH_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    #env(VARNISH_URL): ''
api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
        api_keys:
            apiKey:
                name: Authorization
                type: header
    title: EasyTransfert API
    #version: 1.0.0
    # Enable the Varnish integration
    http_cache:
        invalidation:
            enabled: true
            #varnish_urls: ['%env(VARNISH_URL)%']
        max_age: 0
        shared_max_age: 3600
        vary: ['Content-Type', 'Authorization']
        public: true
    formats:
        jsonld:   ['application/ld+json']
        json:     ['application/json']
        html:     ['text/html']
        jsonhal:  ['application/hal+json']
    collection:
        pagination:
            items_per_page: 30
            client_items_per_page: true